# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Local Explanations for Deep Learning Models
tagline: Local Explanations for Deep Learning Models
description: CS 5966/6966, Fall 2022
author: Ana Marasović
baseurl: # # the subpath of your site, e.g. /blog
url: 'https://utah-explainability-fall22.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
repository: 'utah-explainability-fall22/utah-explainability-fall22.github.io'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "DUTIES.md"]

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
# theme: minima
color_scheme: foo
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
footer_content:

quick_links:
  - name: Reading List
    url: "https://docs.google.com/document/d/1p_8tzU8jgp0wHe4Cb2HWm8SEJ9IQU1p-kXpxlZjNdZ4/edit"
  - name: Google Drive
    url: "https://drive.google.com/drive/u/1/folders/15eLW-7qMSF58FLYaHTm91MWd80fykGps"
  - name: Mattermost
    url: "https://mattermost.cs.washington.edu/ethnlp-wi22"

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  assignments:
    permalink: "/:collection/:path/"
    output: true

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: assignments
    values:
      layout: default

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    assignments:
      # Give the collection a name
      name: Assignments
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
